[general]
name = "minilib-app"
version = "0.6.0"
fix_version = "1.2.0"
authors = ["pt9999"]
license = "MIT"

[build]
opt_level = "basic"
files = [
    "lib/app/clap.fix",
]

[build.test]
opt_level = "basic"
files = [
    "tests/test.fix",
    "tests/app/clap_test.fix",
]

[[dependencies]]
name = "minilib-common"
version = "*"
# path = "../fixlang-minilib-common"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }


[[dependencies]]
name = "hashmap"
version = "*"
git = { url = "https://github.com/tttmmmyyyy/fixlang-hashmap.git" }
